### ISSUE TITLE
Paste a magnet link, it is loading forever

### ISSUE THREAD

**Issue by moracabanas** [codealchemist/watchtor#1]
Hi, first, awesome work. Im looking for a webtorrent based "web based" magnet video player. I Tried watchtor but as description says when I paste a magnet link, it never starts to play just loading.

**Comment by codealchemist** [comment]
Hi @moracabanas!
For torrents to be loaded in Watchtor they need to be available on the WebTorrent network and be encoded in a browser compatible format.
These are the main reasons for a video not to be working on Watchtor.
