### ISSUE TITLE
Page is down

### ISSUE THREAD

**Issue by filmaidykai** [codealchemist/watchtor#2]
Just wanna ask page was shut down or just couple errors and its not working for it?  did you fix it or not?  thanks

**Comment by filmaidykai** [comment]
Again me...  something wrong nearly its will be like one week they gave web page error....

**Comment by filmaidykai** [comment]
There's nothing here, yet.
Build something amazing   they giving this problem when trying to connect to the webpage

**Comment by codealchemist** [comment]
I hosted the app as a demo.
Anyone is welcome to take this repo and host it if you want to.

For the time being I'm trying https://open-watchtor.hashbase.io as an experiment.
Cheers!
